name: kw_dormitory
description: KW Dormitory Service Application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^4.0.6
  provider: ^6.0.4

  kakao_flutter_sdk: ^1.2.2

  firebase_core: ^2.2.0
  firebase_messaging: ^14.1.0

  flutter_local_notifications: ^12.0.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - asset/images/
  
  fonts:
    - family: NanumSquare
      fonts:
        - asset: asset/fonts/NanumSquare-Light.otf
          weight: 300
        - asset: asset/fonts/NanumSquare-Regular.otf
          weight: 400
        - asset: asset/fonts/NanumSquare-Bold.otf
          weight: 700
        - asset: asset/fonts/NanumSquare-ExtraBold.otf
          weight: 800
