name: kw_dormitory
description: KW Dormitory Service Application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^4.0.6
  provider: ^6.0.4

  percent_indicator: ^4.0.1
  webview_flutter: ^3.0.4
  kakaomap_webview: ^0.6.2
  url_launcher: ^6.1.6
  
  kakao_flutter_sdk_user: ^1.3.0-beta.4

  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.1

  flutter_local_notifications: ^12.0.3+1
  shared_preferences: ^2.0.15
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - asset/images/
  
  fonts:
    - family: NanumSquare
      fonts:
        - asset: asset/fonts/NanumSquare-Light.otf
          weight: 300
        - asset: asset/fonts/NanumSquare-Regular.otf
          weight: 400
        - asset: asset/fonts/NanumSquare-Bold.otf
          weight: 700
        - asset: asset/fonts/NanumSquare-ExtraBold.otf
          weight: 800

    - family: GmarketSans
      fonts:
        - asset: asset/fonts/GmarketSans-Light.otf
          weight: 300
        - asset: asset/fonts/GmarketSans-Medium.otf
          weight: 500
        - asset: asset/fonts/GmarketSans-Bold.otf
          weight: 700
