name: kw_dormitory
description: KW Dormitory Service Application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^4.0.6
  provider: ^6.0.4

  kakao_flutter_sdk: ^1.2.2

  firebase_core: ^2.2.0
  firebase_messaging: ^14.1.0

  flutter_local_notifications: ^12.0.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
